Added paper details to Paper View
SE-UUlm/snowballr-frontend pull request #144
Opened 2024-12-18 07:24 UTC by Slartibartfass2

Closes #41 

## What I have made

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- [ ] I have updated the documentation accordingly and commented my code
- [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] unit tests
  - [ ] integration tests
  - [ ] end-to-end tests
- [ ] (for reviewer) I have checked the implementation against the requirements

2025-01-21 20:31 UTC, luca-schlecker requested changes
The page looks great, nice work. :+1: 

I stumbled upon issues with the integration tests though, I attached some details in the form of a log.
The pipeline doesn't seem to encounter the same problem.

Due to the upcoming gRPC work, I did not review changes regarding controllers or backend APIs.

[log.txt](https://github.com/user-attachments/files/18496177/log.txt)

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +        loadingPaperId: Promise<number>;
What's your reasoning for pulling that promise inside this component?
Couldn't this component be used as is when wrapped in svelte's `{#await ...}`?

This question arises multiple times throughout the code, one comment thread is enough though imo.

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/input/ToggleableInput.svelte
> +    use:inputAction={inputActionProps}
Do you think this workaround is necessary? The abstract's `textarea` could instead fill the remaining space. It would reduce complexity with the caveat of always filling the remaining space even when provided with a short text (see image below). Visually there wouldn't be too much of a difference with that one exception.

![image](https://github.com/user-attachments/assets/8683ca3a-237b-4848-b7bf-3f9b5b2cb5ff)

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/PaperInfo.svelte
> +            {/if}
Is there a reason the `id` could be missing?

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/PaperDetail.svelte
> +        value: unknown;
As far as I can tell `value` is used for class names and content at the same time. This should probably be explained somewhere.

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/cards/PaperDetailsCard.svelte
> +        });
I recognize a common pattern: Instead of relying on svelte's `{#await ...}` a state rune is used with a default value. In case you want to avoid `{#await ...}` (previous comment), I'd recommend simplifying that behavior similar to [what is shown here:](https://dev.to/jdgamble555/async-fetching-in-svelte-5-826)
```typescript
// resource.svelte.ts

export let resource = <T>(
    fn: () => Promise<T>,
    initialValue?: T
) => {

    const _rune = $state<{ value: T | undefined }>({
        value: initialValue
    });

    $effect(() => {
        fn().then((data) => {
            _rune.value = data;
        });
    });

    return _rune;
};
```

This could also be extended with a default error value. Maybe something like this:
```typescript
export let resource = <T>(
    fn: () => Promise<T>,
    initialValue?: T,
    onSuccess: (...) => T,
    onError?: (...) => T
) => { ... }
```

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/cards/PaperDetailsCard.svelte
> +                <Skeleton class="flex h-[1.625rem] rounded-full w-[90%]" />
```suggestion
                {#each [100,95,70,82,50,75,90] as width}
                    <Skeleton class="flex h-[1.625rem] rounded-full w-[{width}%]" />
                {/each}
```

2025-01-21 20:31 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/decision-buttons/DecisionButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
Why not a nullable id?

2025-01-21 20:31 UTC, luca-schlecker commented on tests/integration/paper-components/paper-view/paper-detail.test.ts
> +    test("When paper loading failed without error, then errot text is shown", async () => {
```suggestion
    test("When paper loading failed without error, then error text is shown", async () => {
```

2025-01-22 11:30 UTC, Slartibartfass2 reviewed
Thank you for the review.


I couldn't reproduce the errors you got in that log. On which commit did you experience that?

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +        loadingPaperId: Promise<number>;
I used this because the component does not heavily rely on the asynchronous loading, i.e., we can just display the component and as soon as the paper is loaded the functionality works as well.
Therefore, wrapping the component in an await block seemed too much to me.

Where else did you notice this?

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/input/ToggleableInput.svelte
> +    use:inputAction={inputActionProps}
What did you use to produce that?

I tried plenty of approaches and none worked when the text overflows. The action was some sort of last resort.

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/PaperInfo.svelte
> +            {/if}
Yes, this is used when the data is only a `PaperSpec` with no ID. This is the case on the paper create page.

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/PaperDetail.svelte
> +        value: unknown;
Great catch! I added it to the component documentation.

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/cards/PaperDetailsCard.svelte
> +                <Skeleton class="flex h-[1.625rem] rounded-full w-[90%]" />
Good catch. I added it.

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/decision-buttons/DecisionButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
Please elaborate.

2025-01-22 11:30 UTC, Slartibartfass2 commented on tests/integration/paper-components/paper-view/paper-detail.test.ts
> +    test("When paper loading failed without error, then errot text is shown", async () => {
Good catch. Changed it.

2025-01-22 11:30 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/cards/PaperDetailsCard.svelte
> +        });
Nice suggestion, I like it. It's way more clean and descriptive now.

2025-02-06 03:45 UTC, luca-schlecker commented on src/lib/components/composites/input/ToggleableInput.svelte
> +    use:inputAction={inputActionProps}
The combination of
```css
flex-grow: 1;
flex-basis: 0;
overflow: scroll;
```
on the abstract.

2025-02-06 03:46 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/PaperInfo.svelte
> +            {/if}
I see, makes sense. 👍

2025-02-06 04:01 UTC, luca-schlecker commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +        loadingPaperId: Promise<number>;
I guess the behavior you are describing is right. 👍 No need to change anything

2025-02-06 04:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/decision-buttons/DecisionButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
Nevermind, I thought the promise could just take a nullable id but that is just nonsense semantically.

2025-02-06 04:05 UTC, luca-schlecker commented
> I couldn't reproduce the errors you got in that log. On which commit did you experience that?
Will have to test it on the machine that produced the errors again. This machine works through the tests nicely. Either fixed or flakey.

2025-02-06 09:14 UTC, Slartibartfass2 commented on src/lib/components/composites/input/ToggleableInput.svelte
> +    use:inputAction={inputActionProps}
I couldn't reproduce this.
Can you apply the changes to a new branch where I can try it for myself?

2025-02-08 12:40 UTC, luca-schlecker reviewed
Looking great 👍. A rebase seems to be needed though.

2025-02-08 17:07 UTC, luca-schlecker requested changes
Only these two minor things are left.

2025-02-08 17:07 UTC, luca-schlecker commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
This could be a call to `resource`.

2025-02-08 17:07 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/decision-buttons/DecisionButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
another call to `resource` here

2025-02-08 17:17 UTC, Slartibartfass2 commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
Great catch, I changed it.

2025-02-08 17:17 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/decision-buttons/DecisionButton.svelte
> +    loadingPaperId.then((id) => (paperId = id)).catch(() => (paperId = undefined));
Great catch, I changed it.

2025-02-08 17:49 UTC, luca-schlecker approved these changes
Looking great! 🚀

2025-02-08 17:52 UTC, merged