Added paper view
SE-UUlm/snowballr-frontend pull request #89
Opened 2024-11-19 09:04 UTC by Slartibartfass2

Closes #34

## What I have made

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- [ ] I have updated the documentation accordingly and commented my code
- [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] unit tests
  - [ ] integration tests
  - [ ] end-to-end tests
- [ ] (for reviewer) I have checked the implementation against the requirements

2024-12-09 11:04 UTC, luca-schlecker requested changes
Great work! There were some things though that stood out to me. Looking forward to hearing your thoughts on these points.

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +    }
I would prefer having something like this in the Html, dropping `state` entirely and calculating `tooltipText` from `isBookmarked` directly:
```svelte
{#if isHovered}
    {#if isBookmarked}
        <BookmarkMinus />
    {:else}
        <BookmarkPlus />
    {/if}
{:else}
    {#if isBookmarked}
        <Bookmark fill="bg-primary" />
    {:else}
        <Bookmark />
    {/if}
{/if}
```

This would decrease handler complexity and increase readability imo.

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/Tooltip.svelte
> +<Tooltip.Provider>
Is there a reason we don't wrap the whole application in a single tooltip provider?

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/PaperView.svelte
> +            <PaperNavigationButton direction="left" href="" />
Maybe adding a tooltip property to the button primitive would be a nice addition. `PaperNavigationButton` adds a whole new component containing primitive logic just for it to be used two times.
What do you think about 'inlining' it using that modified button primitive?

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/PaperView.svelte
> +                </div>
Same here as with the `PaperNavigationButton`. Inlining may be useful.

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/cards/PaperCard.svelte
> +            <Card.Content class="p-5">
Why is `Tabs.Content` not used here?

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/cards/PaperCard.svelte
Would it be desirable to extract just the specially styled tab bar into a component that then could be used inside a card?

2024-12-09 11:04 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/cards/PaperResearchContextCard.svelte
> +        { value: "1", label: "References/Citations" },
Maybe stick to forward- and backward-references?

2024-12-09 22:21 UTC, Slartibartfass2 reviewed
Thanks for the review, I'll rebase when we're finished so that you see the changes I made.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/PaperView.svelte
> +            <PaperNavigationButton direction="left" href="" />
The Tooltip Trigger is a button itself, so there's no need to add it to the button primitive.
I think it's nice to hide the implementation details in this `PaperView` component, which is big enough, so that one can easily see which buttons are where without having to figure that out by their code and styling.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/PaperView.svelte
> +                </div>
Same as with the `PaperNavigationButton`s, this would add a lot of duplicated code and make the component less readable.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/PaperBookmarkButton.svelte
> +    }
Great suggestion, I like it.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/cards/PaperCard.svelte
> +            <Card.Content class="p-5">
`Tabs.Content` is used in `PaperCardContent` to switch between the different card contents.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/cards/PaperResearchContextCard.svelte
> +        { value: "1", label: "References/Citations" },
Changed it.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/Tooltip.svelte
> +<Tooltip.Provider>
I didn't think of that yet, in the usage description it was always at one place. I think in principle we could do that, but I don't really see the advantage of that. It would remove the advantage of being able to control e.g. the delay for a certain tooltip and would probably be just confusing for others to read.

2024-12-09 22:21 UTC, Slartibartfass2 commented on src/lib/components/composites/paper-components/paper-view/cards/PaperCard.svelte
We don't use it anywhere else, but I like the idea and moved it to a separate component.

2024-12-17 23:53 UTC, luca-schlecker approved these changes
LGTM. :+1:

2024-12-17 23:53 UTC, luca-schlecker commented on src/lib/components/composites/paper-components/paper-view/PaperView.svelte
> +            <PaperNavigationButton direction="left" href="" />
I can see why you'd like to keep it this way. Fine with me :+1: .

2024-12-18 05:40 UTC, merged